# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/vivado_prj/DOA_rearanged_vivado.runs/synth_1/DOA_rearanged.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7s25ftgb196-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/vivado_prj/DOA_rearanged_vivado.cache/wt} [current_project]
set_property parent.project_path {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/vivado_prj/DOA_rearanged_vivado.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_vhdl -library xil_defaultlib {
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Complex3Multiply.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Complex3Multiply_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Complex3Multiply_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Complex3Multiply_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/CordicKernelMag.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/CordicKernelMag_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/CordicKernelMag_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/CordicKernelMag_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Sample_and_Hold_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/DOA_rearanged_pkg.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem_block3.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Fenetrage.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Signal_Trigger.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/TWDLROM_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/SimpleDualPortRAM_generic.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMORY_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_BTFSEL_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2_BUTTERFLY_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMSEL_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_CTRL_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_OUTMux_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_HDL_Optimized_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Mapper_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Correction_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/HDL_CMA_core_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_Hydro_Ref.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem_block2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Sample_and_Hold.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Sample_and_Hold4.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Sample_and_Hold1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Maximum_Hydro_Ref.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/TWDLROM.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMORY.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_BTFSEL.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2_BUTTERFLY.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMSEL.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_CTRL.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_OUTMux.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_HDL_Optimized.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Mapper.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Correction.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/HDL_CMA_core.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_Hydro_1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Maximum_Hydro_1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/TWDLROM_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMORY_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_BTFSEL_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2_BUTTERFLY_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMSEL_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_CTRL_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_OUTMux_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_HDL_Optimized_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Mapper_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Correction_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/HDL_CMA_core_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_Hydro_2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem_block.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Maximum_Hydro_2.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/TWDLROM_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMORY_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_BTFSEL_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2_BUTTERFLY_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_MEMSEL_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_CTRL_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/MINRESRX2FFT_OUTMux_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_HDL_Optimized_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Mapper_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Quadrant_Correction_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/HDL_CMA_core_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/FFT_Hydro_3.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem_block1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Maximum_Hydro_3.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Triggered_Subsystem1.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/Subsystem4.vhd}
  {C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/DOA_rearanged.vhd}
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/clock_constraint.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/franc/OneDrive/Documents techniques/ETS/SONIA/Hydro software/Hydro_Update/slprj/hdlsrc/DOA_rearanged/clock_constraint.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top DOA_rearanged -part xc7s25ftgb196-1 -mode out_of_context
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef DOA_rearanged.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file DOA_rearanged_utilization_synth.rpt -pb DOA_rearanged_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
