-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\franc\OneDrive\Documents techniques\ETS\SONIA\Hydro software\Hydro_Update\slprj\hdlsrc\DOA_rearanged\DOA_rearanged.vhd
-- Created: 2021-06-21 21:49:40
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Model base rate: 3.90625e-06
-- Target subsystem base rate: 3.90625e-06
-- 
-- 
-- Clock Enable  Sample Time
-- -------------------------------------------------------------
-- ce_out        3.90625e-06
-- -------------------------------------------------------------
-- 
-- 
-- Output Signal                 Clock Enable  Sample Time
-- -------------------------------------------------------------
-- PhaseRef                      ce_out        3.90625e-06
-- Phase1                        ce_out        3.90625e-06
-- Phase2                        ce_out        3.90625e-06
-- Phase3                        ce_out        3.90625e-06
-- SNR_Check                     ce_out        3.90625e-06
-- Index                         ce_out        3.90625e-06
-- -------------------------------------------------------------
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: DOA_rearanged
-- Source Path: DOA_rearanged
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY DOA_rearanged IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        clk_enable                        :   IN    std_logic;
        Canal1                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal2                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal3                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Canal4                            :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        Enable                            :   IN    std_logic;
        Signal_Threshold                  :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        SNR_Threshold                     :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
        ce_out                            :   OUT   std_logic;
        PhaseRef                          :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Phase1                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Phase2                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        Phase3                            :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
        SNR_Check                         :   OUT   std_logic;
        Index                             :   OUT   std_logic_vector(16 DOWNTO 0)  -- ufix17
        );
END DOA_rearanged;


ARCHITECTURE rtl OF DOA_rearanged IS

  -- Component Declarations
  COMPONENT Signal_Trigger
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data_in                         :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          Ready                           :   IN    std_logic;
          Enable                          :   IN    std_logic;
          Signal_Threshold                :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          coeff                           :   OUT   std_logic_vector(8 DOWNTO 0);  -- ufix9_En8
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_Ref
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic;
          FFT_ready                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Maximum_Hydro_Ref
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Signal_rsvd                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_In                        :   IN    std_logic;
          Signal_Max                      :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase_Max                       :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_Out                       :   OUT   std_logic;
          Index                           :   OUT   std_logic_vector(16 DOWNTO 0)  -- ufix17
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Maximum_Hydro_1
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Signal_rsvd                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_In                        :   IN    std_logic;
          Phase_Max                       :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Maximum_Hydro_2
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Signal_rsvd                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_In                        :   IN    std_logic;
          Phase_Max                       :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
          );
  END COMPONENT;

  COMPONENT FFT_Hydro_3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Data                            :   IN    std_logic_vector(24 DOWNTO 0);  -- ufix25_En8
          Valid_in                        :   IN    std_logic;
          Magnitude                       :   OUT   std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   OUT   std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_out                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT Maximum_Hydro_3
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          Signal_rsvd                     :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          Phase                           :   IN    std_logic_vector(28 DOWNTO 0);  -- sfix29_En26
          Valid_In                        :   IN    std_logic;
          Phase_Max                       :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
          );
  END COMPONENT;

  COMPONENT Subsystem4
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          a                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          validIn_sum                     :   IN    std_logic;
          alphaValue                      :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En8
          validIn_Max                     :   IN    std_logic;
          SNR_Threshold                   :   IN    std_logic_vector(15 DOWNTO 0);  -- uint16
          SNR_check                       :   OUT   std_logic
          );
  END COMPONENT;

  -- Component Configuration Statements
  FOR ALL : Signal_Trigger
    USE ENTITY work.Signal_Trigger(rtl);

  FOR ALL : FFT_Hydro_Ref
    USE ENTITY work.FFT_Hydro_Ref(rtl);

  FOR ALL : Maximum_Hydro_Ref
    USE ENTITY work.Maximum_Hydro_Ref(rtl);

  FOR ALL : FFT_Hydro_1
    USE ENTITY work.FFT_Hydro_1(rtl);

  FOR ALL : Maximum_Hydro_1
    USE ENTITY work.Maximum_Hydro_1(rtl);

  FOR ALL : FFT_Hydro_2
    USE ENTITY work.FFT_Hydro_2(rtl);

  FOR ALL : Maximum_Hydro_2
    USE ENTITY work.Maximum_Hydro_2(rtl);

  FOR ALL : FFT_Hydro_3
    USE ENTITY work.FFT_Hydro_3(rtl);

  FOR ALL : Maximum_Hydro_3
    USE ENTITY work.Maximum_Hydro_3(rtl);

  FOR ALL : Subsystem4
    USE ENTITY work.Subsystem4(rtl);

  -- Signals
  SIGNAL Canal1_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL FFT_Hydro_Ref_out4               : std_logic;
  SIGNAL Signal_Trigger_out1              : std_logic_vector(8 DOWNTO 0);  -- ufix9
  SIGNAL Signal_Trigger_out2              : std_logic;
  SIGNAL Signal_Trigger_out1_unsigned     : unsigned(8 DOWNTO 0);  -- ufix9_En8
  SIGNAL Product3_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_Ref_out1               : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_Ref_out2               : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_Ref_out3               : std_logic;
  SIGNAL Maximum_Hydro_Ref_out1           : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL Maximum_Hydro_Ref_out2           : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Maximum_Hydro_Ref_out3           : std_logic;
  SIGNAL Maximum_Hydro_Ref_out4           : std_logic_vector(16 DOWNTO 0);  -- ufix17
  SIGNAL Canal2_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product_out1                     : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_1_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_1_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_1_out3                 : std_logic;
  SIGNAL Maximum_Hydro_1_out2             : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Canal3_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product1_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_2_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_2_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_2_out3                 : std_logic;
  SIGNAL Maximum_Hydro_2_out2             : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Canal4_unsigned                  : unsigned(15 DOWNTO 0);  -- uint16
  SIGNAL Product2_out1                    : unsigned(24 DOWNTO 0);  -- ufix25_En8
  SIGNAL FFT_Hydro_3_out1                 : std_logic_vector(26 DOWNTO 0);  -- ufix27
  SIGNAL FFT_Hydro_3_out2                 : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL FFT_Hydro_3_out3                 : std_logic;
  SIGNAL Maximum_Hydro_3_out2             : std_logic_vector(28 DOWNTO 0);  -- ufix29
  SIGNAL Subsystem4_out1                  : std_logic;

BEGIN
  u_Signal_Trigger : Signal_Trigger
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Data_in => Canal1,  -- uint16
              Ready => FFT_Hydro_Ref_out4,
              Enable => Enable,
              Signal_Threshold => Signal_Threshold,  -- uint16
              coeff => Signal_Trigger_out1,  -- ufix9_En8
              Valid_out => Signal_Trigger_out2
              );

  u_FFT_Hydro_Ref : FFT_Hydro_Ref
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Data => std_logic_vector(Product3_out1),  -- ufix25_En8
              Valid_in => Signal_Trigger_out2,
              Magnitude => FFT_Hydro_Ref_out1,  -- sfix27_En8
              Phase => FFT_Hydro_Ref_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_Ref_out3,
              FFT_ready => FFT_Hydro_Ref_out4
              );

  u_Maximum_Hydro_Ref : Maximum_Hydro_Ref
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Signal_rsvd => FFT_Hydro_Ref_out1,  -- sfix27_En8
              Phase => FFT_Hydro_Ref_out2,  -- sfix29_En26
              Valid_In => FFT_Hydro_Ref_out3,
              Signal_Max => Maximum_Hydro_Ref_out1,  -- sfix27_En8
              Phase_Max => Maximum_Hydro_Ref_out2,  -- sfix29_En26
              Valid_Out => Maximum_Hydro_Ref_out3,
              Index => Maximum_Hydro_Ref_out4  -- ufix17
              );

  u_FFT_Hydro_1 : FFT_Hydro_1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Data => std_logic_vector(Product_out1),  -- ufix25_En8
              Valid_in => Signal_Trigger_out2,
              Magnitude => FFT_Hydro_1_out1,  -- sfix27_En8
              Phase => FFT_Hydro_1_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_1_out3
              );

  u_Maximum_Hydro_1 : Maximum_Hydro_1
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Signal_rsvd => FFT_Hydro_1_out1,  -- sfix27_En8
              Phase => FFT_Hydro_1_out2,  -- sfix29_En26
              Valid_In => FFT_Hydro_1_out3,
              Phase_Max => Maximum_Hydro_1_out2  -- sfix29_En26
              );

  u_FFT_Hydro_2 : FFT_Hydro_2
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Data => std_logic_vector(Product1_out1),  -- ufix25_En8
              Valid_in => Signal_Trigger_out2,
              Magnitude => FFT_Hydro_2_out1,  -- sfix27_En8
              Phase => FFT_Hydro_2_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_2_out3
              );

  u_Maximum_Hydro_2 : Maximum_Hydro_2
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Signal_rsvd => FFT_Hydro_2_out1,  -- sfix27_En8
              Phase => FFT_Hydro_2_out2,  -- sfix29_En26
              Valid_In => FFT_Hydro_2_out3,
              Phase_Max => Maximum_Hydro_2_out2  -- sfix29_En26
              );

  u_FFT_Hydro_3 : FFT_Hydro_3
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Data => std_logic_vector(Product2_out1),  -- ufix25_En8
              Valid_in => Signal_Trigger_out2,
              Magnitude => FFT_Hydro_3_out1,  -- sfix27_En8
              Phase => FFT_Hydro_3_out2,  -- sfix29_En26
              Valid_out => FFT_Hydro_3_out3
              );

  u_Maximum_Hydro_3 : Maximum_Hydro_3
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              Signal_rsvd => FFT_Hydro_3_out1,  -- sfix27_En8
              Phase => FFT_Hydro_3_out2,  -- sfix29_En26
              Valid_In => FFT_Hydro_3_out3,
              Phase_Max => Maximum_Hydro_3_out2  -- sfix29_En26
              );

  u_Subsystem4 : Subsystem4
    PORT MAP( clk => clk,
              reset => reset,
              enb => clk_enable,
              a => FFT_Hydro_Ref_out1,  -- sfix27_En8
              validIn_sum => FFT_Hydro_Ref_out3,
              alphaValue => Maximum_Hydro_Ref_out1,  -- sfix27_En8
              validIn_Max => Maximum_Hydro_Ref_out3,
              SNR_Threshold => SNR_Threshold,  -- uint16
              SNR_check => Subsystem4_out1
              );

  Canal1_unsigned <= unsigned(Canal1);

  Signal_Trigger_out1_unsigned <= unsigned(Signal_Trigger_out1);

  Product3_out1 <= Canal1_unsigned * Signal_Trigger_out1_unsigned;

  Canal2_unsigned <= unsigned(Canal2);

  Product_out1 <= Signal_Trigger_out1_unsigned * Canal2_unsigned;

  Canal3_unsigned <= unsigned(Canal3);

  Product1_out1 <= Signal_Trigger_out1_unsigned * Canal3_unsigned;

  Canal4_unsigned <= unsigned(Canal4);

  Product2_out1 <= Signal_Trigger_out1_unsigned * Canal4_unsigned;

  ce_out <= clk_enable;

  PhaseRef <= Maximum_Hydro_Ref_out2;

  Phase1 <= Maximum_Hydro_1_out2;

  Phase2 <= Maximum_Hydro_2_out2;

  Phase3 <= Maximum_Hydro_3_out2;

  SNR_Check <= Subsystem4_out1;

  Index <= Maximum_Hydro_Ref_out4;

END rtl;

