-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\franc\OneDrive\Documents techniques\ETS\SONIA\Hydro software\Hydro_Update\slprj\hdlsrc\DOA_rearanged\Quadrant_Correction.vhd
-- Created: 2021-06-21 21:49:39
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Quadrant_Correction
-- Source Path: DOA_rearanged/FFT Hydro 1/HDL_CMA_core/Quadrant_Correction
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Quadrant_Correction IS
  PORT( zin                               :   IN    std_logic_vector(26 DOWNTO 0);  -- sfix27_En26
        QA_Control                        :   IN    std_logic_vector(2 DOWNTO 0);  -- ufix3
        zout                              :   OUT   std_logic_vector(28 DOWNTO 0)  -- sfix29_En26
        );
END Quadrant_Correction;


ARCHITECTURE rtl OF Quadrant_Correction IS

  -- Signals
  SIGNAL QA_Control_unsigned              : unsigned(2 DOWNTO 0);  -- ufix3
  SIGNAL xyNegative                       : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL AbsRel                           : std_logic;  -- ufix1
  SIGNAL pidivtwo                         : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL zin_signed                       : signed(26 DOWNTO 0);  -- sfix27_En26
  SIGNAL zCast                            : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL pivdivtwosubout                  : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL mux1out                          : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL Negation_cast                    : signed(29 DOWNTO 0);  -- sfix30_En26
  SIGNAL Negation_cast_1                  : signed(29 DOWNTO 0);  -- sfix30_En26
  SIGNAL Negation_cast_2                  : signed(30 DOWNTO 0);  -- sfix31_En26
  SIGNAL mux1out_negate                   : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL pionepos                         : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL pi_subtraction                   : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL pioneneg                         : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL negpi_addition                   : signed(28 DOWNTO 0);  -- sfix29_En26
  SIGNAL mux2out                          : signed(28 DOWNTO 0);  -- sfix29_En26

BEGIN
  QA_Control_unsigned <= unsigned(QA_Control);

  xyNegative <= QA_Control_unsigned(1 DOWNTO 0);

  AbsRel <= QA_Control_unsigned(2);

  pidivtwo <= to_signed(16#06487ED5#, 29);

  zin_signed <= signed(zin);

  zCast <= resize(zin_signed, 29);

  pivdivtwosubout <= pidivtwo - zCast;

  
  mux1out <= pivdivtwosubout WHEN AbsRel = '0' ELSE
      zCast;

  Negation_cast <= resize(mux1out, 30);
  Negation_cast_1 <=  - (Negation_cast);
  Negation_cast_2 <= resize(Negation_cast_1, 31);
  mux1out_negate <= Negation_cast_2(28 DOWNTO 0);

  pionepos <= to_signed(16#0C90FDAA#, 29);

  pi_subtraction <= pionepos - mux1out;

  pioneneg <= to_signed(-16#0C90FDAB#, 29);

  negpi_addition <= pioneneg + mux1out;

  
  mux2out <= mux1out WHEN xyNegative = to_unsigned(16#0#, 2) ELSE
      mux1out_negate WHEN xyNegative = to_unsigned(16#1#, 2) ELSE
      pi_subtraction WHEN xyNegative = to_unsigned(16#2#, 2) ELSE
      negpi_addition;

  zout <= std_logic_vector(mux2out);

END rtl;

