vlib work
vcom  Test_DOA_pkg.vhd
vcom  Calcul_Direction.vhd
vcom  Quadrant_Mapper.vhd
vcom  CordicKernelMag.vhd
vcom  Quadrant_Correction.vhd
vcom  HDL_CMA_core.vhd
vcom  TWDLROM.vhd
vcom  MINRESRX2FFT_CTRL.vhd
vcom  SimpleDualPortRAM_generic.vhd
vcom  MINRESRX2FFT_MEMORY.vhd
vcom  MINRESRX2FFT_BTFSEL.vhd
vcom  Complex3Multiply.vhd
vcom  MINRESRX2_BUTTERFLY.vhd
vcom  MINRESRX2FFT_MEMSEL.vhd
vcom  MINRESRX2FFT_OUTMux.vhd
vcom  FFT_HDL_Optimized.vhd
vcom  FFT_Hydro_1.vhd
vcom  Quadrant_Mapper_block.vhd
vcom  CordicKernelMag_block.vhd
vcom  Quadrant_Correction_block.vhd
vcom  HDL_CMA_core_block.vhd
vcom  TWDLROM_block.vhd
vcom  MINRESRX2FFT_CTRL_block.vhd
vcom  MINRESRX2FFT_MEMORY_block.vhd
vcom  MINRESRX2FFT_BTFSEL_block.vhd
vcom  Complex3Multiply_block.vhd
vcom  MINRESRX2_BUTTERFLY_block.vhd
vcom  MINRESRX2FFT_MEMSEL_block.vhd
vcom  MINRESRX2FFT_OUTMux_block.vhd
vcom  FFT_HDL_Optimized_block.vhd
vcom  FFT_Hydro_2.vhd
vcom  Quadrant_Mapper_block1.vhd
vcom  CordicKernelMag_block1.vhd
vcom  Quadrant_Correction_block1.vhd
vcom  HDL_CMA_core_block1.vhd
vcom  TWDLROM_block1.vhd
vcom  MINRESRX2FFT_CTRL_block1.vhd
vcom  MINRESRX2FFT_MEMORY_block1.vhd
vcom  MINRESRX2FFT_BTFSEL_block1.vhd
vcom  Complex3Multiply_block1.vhd
vcom  MINRESRX2_BUTTERFLY_block1.vhd
vcom  MINRESRX2FFT_MEMSEL_block1.vhd
vcom  MINRESRX2FFT_OUTMux_block1.vhd
vcom  FFT_HDL_Optimized_block1.vhd
vcom  FFT_Hydro_3.vhd
vcom  Quadrant_Mapper_block2.vhd
vcom  CordicKernelMag_block2.vhd
vcom  Quadrant_Correction_block2.vhd
vcom  HDL_CMA_core_block2.vhd
vcom  TWDLROM_block2.vhd
vcom  MINRESRX2FFT_CTRL_block2.vhd
vcom  MINRESRX2FFT_MEMORY_block2.vhd
vcom  MINRESRX2FFT_BTFSEL_block2.vhd
vcom  Complex3Multiply_block2.vhd
vcom  MINRESRX2_BUTTERFLY_block2.vhd
vcom  MINRESRX2FFT_MEMSEL_block2.vhd
vcom  MINRESRX2FFT_OUTMux_block2.vhd
vcom  FFT_HDL_Optimized_block2.vhd
vcom  FFT_Hydro_Ref.vhd
vcom  Sample_and_Hold.vhd
vcom  SampleHold.vhd
vcom  Trigger.vhd
vcom  FFTs.vhd
vcom  Sample_and_Hold_block.vhd
vcom  SampleHold_block.vhd
vcom  Sample_and_Hold_block1.vhd
vcom  SampleHold5.vhd
vcom  Subsystem.vhd
vcom  Maximum_Hydro_1.vhd
vcom  Subsystem_block.vhd
vcom  Maximum_Hydro_2.vhd
vcom  Subsystem_block1.vhd
vcom  Maximum_Hydro_3.vhd
vcom  Sample_and_Hold_block2.vhd
vcom  SampleHold3.vhd
vcom  Subsystem_block2.vhd
vcom  Maximum_Hydro_Ref.vhd
vcom  Division.vhd
vcom  SNR_Check.vhd
vcom  Test_DOA.vhd
